### PR TITLE
Completely revamped the ;noob-scripter command

### PR DESCRIPTION
**Pull request by SSolarite**
I have comp;etely revamped the ;noob-scripter command with a new, clean embed - This embed was made using [Discohook](https://discohook.org)

### CODE REVIEW

**Comment by cloewen8** [comment]
What would be the benefit in making this an embed?

**Comment by SSolarite** [comment]
I believe it would look more presentable and clean.

**Review by cloewen8 — APPROVED** [review]
Would definitely help to reduce spam with all of the link previews.

**Comment by cloewen8** [comment]
Will take some time to properly add this embed to the server

**Pull request merged**
