### PR TITLE
Added webhook friendly version and edited rules

### PR DESCRIPTION
**Pull request by CaptainStabs**
Made rules sound less childish

### CODE REVIEW

**Comment by cloewen8** [comment]
Also a "webhook friendly version"? What does this change that is more friendly to webhooks?

**Review by cloewen8 — CHANGES_REQUESTED** [review]
Please keep the rules in a single file (Roblox Developers Server Rules.md). Only change.

**Comment by CaptainStabs** [comment]
Removed

**Review by cloewen8 — APPROVED** [review]
You could of merged the 2 files together. Regardless, I'm happy with this change.

**Pull request merged**
