### PR TITLE
Update 1 - Proposed NSFW Clarification

### PR DESCRIPTION
**Pull request by qvthc**
This update shall clarify the use of suggestive gifs/media across the server. This should now be perfectly see-able by all members in the server, holding moderators accountable to moderate them.

# Use the one on the bottom (latest)

### CODE REVIEW

**Comment by qvthc** [comment]
grrrr

**Comment by DighNo** [comment]
👍

**Comment by qvthc** [comment]
frfr

**Comment by WhoCutTheCheese** [comment]
Changes are under review by the Roblox Developers' administration.
Hang tight!

**Comment by DighNo** [comment]
email

**Review by cloewen8 — CHANGES_REQUESTED** [review]
I don't believe the term lampshading is common enough for a majority of members to understand. Consider an alternative.
I'm also concerned with it being based on member perspective and the overall subjectivity of it. Please consider limiting what is covered or making it more specific.

**Comment by Aimarekin** [comment]
"any members' perspective" is imo too broad, I know it was already there before this PR but I believe it should be changed regardless.

EDIT: For example, in certain religions there's clothes that are considered too revealing and sexually inciting that I don't believe should be restricted by our rules.

**Comment by qvthc** [comment]
Thanks for everyone requesting changes, they look great.

**Review by qvthc — COMMENTED** [review]
Implemented

**Comment by WhoCutTheCheese** [comment]
Changes to NSFW content definitions coming in the next rules revisions, thank you!

**Pull request closed without merging**
